SnowStore.Web/ViewModels/ResourcesManage/CategoryViewModel.cs
namespace SnowStore.Web.ViewModels.ResourcesManage
{
    public class CategoryViewModel
    {
        public string Name { get; set; }
    }
}

SnowStore.Web/ViewModels/ResourcesManage/ProductViewModel.cs
namespace SnowStore.Web.ViewModels.ResourcesManage
{
    public class ProductViewModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
        // можно ли использовать трансформатор на вью модель, чтобы тут было поле с объектом
        // public Category Category { get; set; }?
        public int CategoryId { get; set; }
        public string Image { get; set; }
        public decimal Price { get; set; }
    }
}

SnowStore.Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using SnowStore.Core.Repositories;

namespace SnowStore.Web.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryRepository categoryRepository;
        private IProductRepository productRepository;
        public CategoryController(ICategoryRepository categoryRepository, IProductRepository productRepository)
        {
            this.categoryRepository = categoryRepository;
            this.productRepository = productRepository;
        }
        
        [Route("/category/{categoryId:int}")]
        [HttpGet]
        public IActionResult Index(int categoryId)
        {
            var category = categoryRepository.FindOneBy(categoryId);
            var products = productRepository.FindAllByCategory(category);
            
            ViewBag.category = category;
            ViewBag.products = products;
            
            return View();
        }
    }
}

SnowStore.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SnowStore.Core.Repositories;

namespace SnowStore.Web.Controllers
{
    public class HomeController : Controller
    {
        private ICategoryRepository categoryRepository;

        public HomeController(ICategoryRepository categoryRepository)
        {
            this.categoryRepository = categoryRepository;
        }
        
        [Route("index")]
        [Route("")]
        public IActionResult Index()
        {
            ViewBag.categories = this.categoryRepository.GetLimitedCategories();
            
            return View();
        }
    }
}

SnowStore.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using SnowStore.Core.Repositories;

namespace SnowStore.Web.Controllers
{
    [Route("/product")]
    public class ProductController : Controller
    {
        private IProductRepository productRepository;
        
        public ProductController(IProductRepository productRepository)
        {
            this.productRepository = productRepository;
        }
        
        [Route("{productId:int}")]
        [HttpGet]
        public IActionResult Index(int productId)
        {
            var product = productRepository.FindOneBy(productId);

            ViewBag.product = product;
            
            return View();
        }
    }
}

SnowStore.Web/Controllers/ResourcesManageController.cs
using Microsoft.AspNetCore.Mvc;
using SnowStore.Core.Entities;
using SnowStore.Core.Repositories;
using SnowStore.Web.Builders.Entities;
using SnowStore.Web.ViewModels.ResourcesManage;

namespace SnowStore.Web.Controllers
{
    public class ResourcesManageController : Controller
    {
        private ICategoryRepository categoryRepository;
        private IProductRepository productRepository;
        private ProductEntityBuilder productEntityBuilder;
        
        public ResourcesManageController(
            ICategoryRepository categoryRepository, 
            IProductRepository productRepository,
            ProductEntityBuilder productEntityBuilder
        ) {
            this.categoryRepository = categoryRepository;
            this.productRepository = productRepository;
            this.productEntityBuilder = productEntityBuilder;
        }
        
        [Route("/resources/manage")]
        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.categories = this.categoryRepository.GetAllCategories();
            return View();
        }

        [Route("/resources/manage/category")]
        [HttpPost]
        public IActionResult AddCategory(CategoryViewModel categoryViewModel)
        {
            var category = new Category
            {
                Name = categoryViewModel.Name
            };

            categoryRepository.Add(category);
            
            return RedirectToAction("Index");
        }

        [Route("/resources/manage/product")]
        [HttpPost]
        public IActionResult AddProduct(ProductViewModel productViewModel)
        {
            var product = productEntityBuilder.Build(productViewModel);

            productRepository.Add(product);
            
            return RedirectToAction("Index");
        }
    }
}

SnowStore.Web/Views/Category/Index.cshtml
@{
    ViewData["Title"] = "Category details";
    Category category = ViewBag.category;
    List<Product> products = ViewBag.products;
}
<h2>Category name: @category.Name</h2>

<h3>Products list:</h3>

@if (products.Count > 0)
{
    <ul class="list-group list-group-horizontal">
        @foreach (var product in products)
        {
            <li class="list-group-item">
                <div style="display: inline-block">
                    <a asp-controller="Product" asp-action="Index" asp-route-productId="@product.Id">
                        <img src="@product.Image"/>
                    </a>
                    <div>
                        <a asp-controller="Product" asp-action="Index" asp-route-productId="@product.Id">
                            @product.Name
                        </a>
                    </div>
                    <div>
                        Price: @product.Price.Value @product.Price.Currency
                    </div>
                    <div>
                        @product.Description
                    </div>
                </div>
            </li>
        }
    </ul>
}
else
{
    <h5>No products!</h5>
}

SnowStore.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Available categories list:</h1>
    
    @if (ViewBag.categories.Count > 0)
    {
        <ul>
            @foreach (Category category in ViewBag.categories)
            {
                <li>
                    <a asp-controller="Category" asp-action="Index" asp-route-categoryId="@category.Id">
                        @category.Name
                    </a>
                </li>
            }
        </ul>
    }
    else
    {
        <h2>No categories available!</h2>
    }
</div>

SnowStore.Web/Views/Product/Index.cshtml
@{
    ViewData["Title"] = "Product details";

    Product product = ViewBag.product;
}

<div class="media">
    <img src="@product.Image" class="align-self-start mr-3" alt="@product.Name">
    <div class="media-body">
        <h5 class="mt-0">@product.Name</h5>
        @product.Description
        <p>
            Price: @product.Price.Value @product.Price.Currency
        </p>
    </div>
</div>

SnowStore.Web/Views/ResourcesManage/Forms/NewCategoryForm.cshtml
@model SnowStore.Web.ViewModels.ResourcesManage.CategoryViewModel

<h2>
    Add new Category
</h2>

<form method="post" asp-action="AddCategory" asp-controller="ResourcesManage">
    <p>
        Category name: <input type="text" name="Name">
    </p>
    <p>
        <input type="submit"/>
    </p>
</form>

SnowStore.Web/Views/ResourcesManage/Forms/NewProductForm.cshtml
@model SnowStore.Web.ViewModels.ResourcesManage.ProductViewModel

<h2>Add new Product</h2>

<form method="post" asp-action="AddProduct" asp-controller="ResourcesManage">
    <p>
        Product name: <input type="text" name="Name">
    </p>
    <p>
        Product image url: <input type="text" name="Image" readonly value="https://via.placeholder.com/350x150">
    </p>
    <p>
        Product Description: 
        <textarea name="Description"></textarea>
    </p>
    <p>
        Product Price:
        <input type="number" step="0.5" name="Price">
    </p>
    <p>
        Product Category:
        <select name="CategoryId">
            @foreach (Category category in ViewBag.categories)
            {
                <option value="@category.Id">@category.Name</option>
            }
        </select>
    </p>
    <p>
        <input type="submit"/>
    </p>
</form>

SnowStore.Web/Views/ResourcesManage/Index.cshtml
@{
    ViewData["Title"] = "Resources manage";
}

<partial name="Forms/NewCategoryForm.cshtml"/>

<partial name="Forms/NewProductForm.cshtml"/>

SnowStore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SnowStore.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index">
                            Home
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - SnowStore.Web
        </div>
    </footer>
</body>
</html>